spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  mail:
    host: smtp.gmail.com
    port: 587
    username: miknieyh@yanolja.com
    password: avnlmtnriwughsxp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379

mailSend:
  userid: "miknieyh@yanolja.com"

server:
  port: 8081

